### ISSUE TITLE
Es un archivo por objeto

### ISSUE THREAD

**Issue by CRAG666** [15oscar/oscar_luis_diaz_grajales_objeto_seguro#1]
Creas y almacenas datos en el archivo del objeto correspondiente. En cuanto a los otros puntos cuando termines tu implementacion escribe issues al respecto y me arrobas.

**Comment by 15oscar** [comment]
@CRAG666 ya subi el archivo maestro diego, es que estaba en el archivo.rar, aun que ahorita ya me revolvi otra vez
